version: "2"

services:
  gotickets:
    image: bitnami/postgresql
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - POSTGRESQL_USERNAME=${DB_USER}
      - POSTGRESQL_PASSWORD=${DB_PASSWORD}
      - POSTGRESQL_DATABASE=${DB_NAME}
